### ISSUE TITLE
CustomItems

### ISSUE THREAD

**Issue by JordanPlayz158** [Pseudooo/NoCrafting#2]
Doesn't stop custom items recipes from being denied when specified in blocked items list

**Comment by Pseudooo** [comment]
This seems to be a result of `CustomItems`. I'm not sure how they're handling their own custom recipes but the recipe indicates my plugin should be _attempting_ to set the result of the recipe, however it still yields a Craftable item.

**Comment by Pseudooo** [comment]
Issue arose from reload as opposed to restarting the server.
